name: Assign preview-domain
on:
  pull_request: # Trigger on pull request
    types: [opened, reopened]

permissions:
  contents: read

jobs:
  assign-preview-domain:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Assign preview-domain
        run: |
          curl -X POST "https://vercel.com/api/v10/projects/${{secrets.VERCEL_PROJECT_ID}}/domains" \
            -H "Authorization: Bearer ${{secrets.VERCEL_BEARER_TOKEN}}" \
            -H "Content-Type: application/json" \
            -d '{"name": "${{ github.head_ref }}.${{ vars.PREVIEW_DOMAIN }}","gitBranch":"${{ github.head_ref }}"}'
      - name: Comment with the assigned preview-domain
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const knownString = 'Preview domain:'
            const pullRequest = await github.rest.pulls.get({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            const hasAlreadyCommented = pullRequest.data.body.includes(knownString)

            if (hasAlreadyCommented) {
              console.log('Already commented once')
            } else {
              console.log('Creating comment for the first time')
              const body = pullRequest.data.body
                ? `${pullRequest.data.body}\n\n${knownString} https://${{ github.head_ref }}.${{ vars.PREVIEW_DOMAIN }}`
                : `${knownString} https://${{ github.head_ref }}.${{ vars.PREVIEW_DOMAIN }}`

              await github.rest.pulls.update({
                pull_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body,
              })
            }
